spring:
  profiles:
    active: dev #默认为开发环境
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.sparksys.authority.infrastructure.client: debug
    com.sparksys.authority.infrastructure.mapper: debug
  file:
    path: C:\logs\${spring.application.name}
